export const header = [
  {
    id: 1,
    title: "خانه",
    category: "",
    submenu: [],
    href: "/",
  },
  {
    id: 2,
    title: "کیف",
    href: "/bags",
    category: "کیف",
    image: "/menu/bag-banner.jpg",
    submenu: [
      {
        id: 1,
        title: "کیف دوشی",
        category: "کیف دوشی",
        href: "/bags/shoulder",
      },
      {
        id: 2,
        title: "کوله پشتی",
        category: "کوله پشتی",
        href: "/bags/backpack",
      },
      { id: 3, title: "کیف دستی", category: "کیف دستی", href: "/bags/handbag" },
      { id: 4, title: "کیف پول", category: "کیف پول", href: "/bags/wallet" },
      {
        id: 5,
        title: "کیف لپ‌تاپ",
        category: "کیف لپ‌تاپ",
        href: "/bags/laptop",
      },
      {
        id: 6,
        title: "کیف مدرسه",
        category: "کیف مدرسه",
        href: "/bags/school",
      },
      { id: 7, title: "کیف چرم", category: "کیف چرم", href: "/bags/leather" },
      {
        id: 8,
        title: "کیف ورزشی",
        category: "کیف ورزشی",
        href: "/bags/sports",
      },
      { id: 9, title: "کیف زنانه", category: "کیف زنانه", href: "/bags/women" },
      {
        id: 10,
        title: "کیف مردانه",
        category: "کیف مردانه",
        href: "/bags/men",
      },
    ],
  },
  {
    id: 3,
    title: "اکسسوری",
    category: "اکسسوری",
    href: "/accessories",
    image: "/menu/accessories-banner.jpg",
    submenu: [
      {
        id: 1,
        title: "جواهرات",
        category: "جواهرات",
        href: "/accessories/jewelry",
      },
      {
        id: 2,
        title: "کمربند",
        category: "کمربند",
        href: "/accessories/belts",
      },
      { id: 3, title: "کلاه", category: "کلاه", href: "/accessories/hats" },
      {
        id: 4,
        title: "دستبند",
        category: "دستبند",
        href: "/accessories/bracelets",
      },
      {
        id: 5,
        title: "گردنبند",
        category: "گردنبند",
        href: "/accessories/necklaces",
      },
      {
        id: 6,
        title: "ساعت مچی",
        category: "ساعت مچی",
        href: "/accessories/watches",
      },
      {
        id: 7,
        title: "عینک آفتابی",
        category: "عینک آفتابی",
        href: "/accessories/sunglasses",
      },
      {
        id: 8,
        title: "کیف پول",
        category: "کیف پول",
        href: "/accessories/wallets",
      },
      {
        id: 9,
        title: "کفش های رسمی",
        category: "کفش های رسمی",
        href: "/accessories/formal-shoes",
      },
      {
        id: 10,
        title: "کمربند چرم",
        category: "کمربند چرم",
        href: "/accessories/leather-belts",
      },
    ],
  },
  {
    id: 4,
    title: "عینک",
    href: "/glasses",
    category: "عینک",
    image: "/menu/glasses-banner.jpg",
    submenu: [
      {
        id: 1,
        title: "عینک آفتابی",
        category: "عینک آفتابی",
        href: "/glasses/sunglasses",
      },
      {
        id: 2,
        title: "عینک طبی",
        category: "عینک طبی",
        href: "/glasses/optical",
      },
      {
        id: 3,
        title: "عینک ورزشی",
        category: "عینک ورزشی",
        href: "/glasses/sports",
      },
      {
        id: 4,
        title: "عینک غواصی",
        category: "عینک غواصی",
        href: "/glasses/diving",
      },
      {
        id: 5,
        title: "عینک کودک",
        category: "عینک کودک",
        href: "/glasses/kids",
      },
      {
        id: 6,
        title: "لنزهای چشمی",
        category: "لنزهای چشمی",
        href: "/glasses/contact-lenses",
      },
      {
        id: 7,
        title: "عینک گرافیکی",
        category: "عینک گرافیکی",
        href: "/glasses/graphic",
      },
    ],
  },
  {
    id: 5,
    title: "کفش",
    href: "/shoes",
    category: "کفش",
    image: "/menu/shoes-banner.jpg",
    submenu: [
      {
        id: 1,
        title: "کفش اسپرت",
        category: "کفش اسپرت",
        href: "/shoes/sport",
      },
      { id: 2, title: "کفش رسمی", category: "کفش رسمی", href: "/shoes/formal" },
      { id: 3, title: "صندل", category: "صندل", href: "/shoes/sandals" },
      {
        id: 4,
        title: "کفش راحتی",
        category: "کفش راحتی",
        href: "/shoes/comfy",
      },
      {
        id: 5,
        title: "کفش کوهنوردی",
        category: "کفش کوهنوردی",
        href: "/shoes/hiking",
      },
      {
        id: 6,
        title: "کفش ورزشی زنانه",
        category: "کفش ورزشی زنانه",
        href: "/shoes/women-sport",
      },
      {
        id: 7,
        title: "کفش ورزشی مردانه",
        category: "کفش ورزشی مردانه",
        href: "/shoes/men-sport",
      },
      { id: 8, title: "چکمه", category: "چکمه", href: "/shoes/boots" },
    ],
  },
  {
    id: 6,
    title: "ساعت",
    href: "/watches",
    category: "ساعت",
    image: "/menu/watch-banner.jpg",
    submenu: [
      {
        id: 1,
        title: "ساعت مچی مردانه",
        category: "ساعت مچی مردانه",
        href: "/watches/men",
      },
      {
        id: 2,
        title: "ساعت مچی زنانه",
        category: "ساعت مچی زنانه",
        href: "/watches/women",
      },
      {
        id: 3,
        title: "ساعت هوشمند",
        category: "ساعت هوشمند",
        href: "/watches/smart",
      },
      {
        id: 4,
        title: "ساعت لوکس",
        category: "ساعت لوکس",
        href: "/watches/luxury",
      },
      {
        id: 5,
        title: "ساعت کلاسیک",
        category: "ساعت کلاسیک",
        href: "/watches/classic",
      },
      {
        id: 6,
        title: "ساعت ورزشی",
        category: "ساعت ورزشی",
        href: "/watches/sport",
      },
    ],
  },

  {
    id: 8,
    title: "کد مرسوله",
    href: "/sender-code",
    category: "",
    submenu: [],
  },
];
