export const header = [
  {
    id: 1,
    title: "خانه",
    submenu: [],
    href: "/",
  },
  {
    id: 2,
    title: "کیف",
    href: "/bags",
    image: "/menu/bag-banner.jpg",
    submenu: [
      { id: 1, title: "کیف دوشی", href: "/bags/shoulder" },
      { id: 2, title: "کوله پشتی", href: "/bags/backpack" },
      { id: 3, title: "کیف دستی", href: "/bags/handbag" },
      { id: 4, title: "کیف پول", href: "/bags/wallet" },
      { id: 5, title: "کیف لپ‌تاپ", href: "/bags/laptop" },
      { id: 6, title: "کیف مدرسه", href: "/bags/school" },
      { id: 7, title: "کیف چرم", href: "/bags/leather" },
      { id: 8, title: "کیف ورزشی", href: "/bags/sports" },
      { id: 9, title: "کیف زنانه", href: "/bags/women" },
      { id: 10, title: "کیف مردانه", href: "/bags/men" },
    ],
  },
  {
    id: 3,
    title: "اکسسوری",
    href: "/accessories",
    image: "/menu/accessories-banner.jpg",
    submenu: [
      { id: 1, title: "جواهرات", href: "/accessories/jewelry" },
      { id: 2, title: "کمربند", href: "/accessories/belts" },
      { id: 3, title: "کلاه", href: "/accessories/hats" },
      { id: 4, title: "دستبند", href: "/accessories/bracelets" },
      { id: 5, title: "گردنبند", href: "/accessories/necklaces" },
      { id: 6, title: "ساعت مچی", href: "/accessories/watches" },
      { id: 7, title: "عینک آفتابی", href: "/accessories/sunglasses" },
      { id: 8, title: "کیف پول", href: "/accessories/wallets" },
      { id: 9, title: "کفش های رسمی", href: "/accessories/formal-shoes" },
      { id: 10, title: "کمربند چرم", href: "/accessories/leather-belts" },
    ],
  },
  {
    id: 4,
    title: "عینک",
    href: "/glasses",
    image: "/menu/glasses-banner.jpg",
    submenu: [
      { id: 1, title: "عینک آفتابی", href: "/glasses/sunglasses" },
      { id: 2, title: "عینک طبی", href: "/glasses/optical" },
      { id: 3, title: "عینک ورزشی", href: "/glasses/sports" },
      { id: 4, title: "عینک غواصی", href: "/glasses/diving" },
      { id: 5, title: "عینک کودک", href: "/glasses/kids" },
      { id: 6, title: "لنزهای چشمی", href: "/glasses/contact-lenses" },
      { id: 7, title: "عینک گرافیکی", href: "/glasses/graphic" },
    ],
  },
  {
    id: 5,
    title: "کفش",
    href: "/shoes",
    image: "/menu/shoes-banner.jpg",
    submenu: [
      { id: 1, title: "کفش اسپرت", href: "/shoes/sport" },
      { id: 2, title: "کفش رسمی", href: "/shoes/formal" },
      { id: 3, title: "صندل", href: "/shoes/sandals" },
      { id: 4, title: "کفش راحتی", href: "/shoes/comfy" },
      { id: 5, title: "کفش کوهنوردی", href: "/shoes/hiking" },
      { id: 6, title: "کفش ورزشی زنانه", href: "/shoes/women-sport" },
      { id: 7, title: "کفش ورزشی مردانه", href: "/shoes/men-sport" },
      { id: 8, title: "چکمه", href: "/shoes/boots" },
    ],
  },
  {
    id: 6,
    title: "ساعت",
    href: "/watches",
    image: "/menu/watch-banner.jpg",
    submenu: [
      { id: 1, title: "ساعت مچی مردانه", href: "/watches/men" },
      { id: 2, title: "ساعت مچی زنانه", href: "/watches/women" },
      { id: 3, title: "ساعت هوشمند", href: "/watches/smart" },
      { id: 4, title: "ساعت لوکس", href: "/watches/luxury" },
      { id: 5, title: "ساعت کلاسیک", href: "/watches/classic" },
      { id: 6, title: "ساعت ورزشی", href: "/watches/sport" },
    ],
  },
  {
    id: 7,
    title: "پوشاک",
    href: "/clothing",
    image: "/menu/cloth-banner.jpg",
    submenu: [
      { id: 1, title: "تی‌شرت", href: "/clothing/tshirt" },
      { id: 2, title: "شلوار", href: "/clothing/pants" },
      { id: 3, title: "کت و کاپشن", href: "/clothing/jackets" },
      { id: 4, title: "پیراهن", href: "/clothing/shirts" },
      { id: 5, title: "کفش و صندل", href: "/clothing/shoes" },
      { id: 6, title: "لباس خواب", href: "/clothing/nightwear" },
      { id: 7, title: "لباس زیر", href: "/clothing/underwear" },
      { id: 8, title: "کیف و کوله پشتی", href: "/clothing/bags" },
    ],
  },
  {
    id: 8,
    title: "کد مرسوله",
    href: "/sender-code",
    submenu: [],
  },
];
