export const sampleProducts = [
  // bags
  {
    name: "کیف دوشی زنانه مدل کلاسیک",
    description: "کیف دوشی سبک با طراحی شیک مناسب استفاده روزمره.",
    sku: "SHD-001",
    price: 520000,
    category: "کیف",
    subcategories: "کیف دوشی",
    stock: 15,
    images: [{ public_id: "bag1", url: "/bags/b10.png" }],
    brand: "AldoGallery",
    discount: 10,
    ratings: 4.5,
    numReviews: 25,
    isFeatured: true,
    color: ["مشکی", "قهوه‌ای"],
    size: ["کوچک", "متوسط"],
    weight: 0.5,
    dimensions: { width: 25, height: 18, depth: 8 },
    warranty: "6 ماه",
  },
  {
    name: "کوله پشتی اسپرت دخترانه",
    description: "مناسب برای دانشجویان و استفاده روزمره.",
    sku: "BKP-002",
    price: 690000,
    category: "کیف",
    subcategories: "کوله پشتی",
    stock: 10,
    images: [{ public_id: "bag1", url: "/bags/b6.png" }],
    brand: "BackZone",
    ratings: 4.0,
    numReviews: 18,
    isFeatured: false,
    color: ["صورتی", "طوسی"],
    size: ["متوسط"],
    weight: 0.9,
    dimensions: { width: 30, height: 40, depth: 15 },
    warranty: "1 سال",
  },
  {
    name: "کیف دستی مجلسی زنانه",
    description: "طراحی لاکچری با بند زنجیری مناسب مجالس.",
    sku: "HDB-003",
    price: 850000,
    category: "کیف",
    subcategories: "کیف دستی",
    stock: 8,
    images: [{ public_id: "bag1", url: "/bags/b9.png" }],
    brand: "Elegant",
    discount: 15,
    ratings: 4.8,
    numReviews: 32,
    isFeatured: true,
    color: ["طلایی", "نقره‌ای"],
    size: ["کوچک"],
    weight: 0.4,
    dimensions: { width: 20, height: 14, depth: 6 },
    warranty: "3 ماه",
  },
  {
    name: "کیف پول مردانه چرم",
    description: "کیف پول کلاسیک از چرم طبیعی با دوام بالا.",
    sku: "WLT-004",
    price: 320000,
    category: "کیف",
    subcategories: "کیف پول",
    stock: 20,
    images: [{ public_id: "bag1", url: "/bags/b2.png" }],
    brand: "LeatherCraft",
    ratings: 4.3,
    numReviews: 14,
    isFeatured: false,
    color: ["قهوه‌ای", "مشکی"],
    size: ["کوچک"],
    weight: 0.2,
    dimensions: { width: 12, height: 9, depth: 2 },
    warranty: "1 سال",
  },
  {
    name: "کیف لپ‌تاپ چرم مصنوعی",
    description: "مناسب برای حمل لپ‌تاپ‌های 15 اینچ.",
    sku: "LTP-005",
    price: 980000,
    category: "کیف",
    subcategories: "کیف لپ‌تاپ",
    stock: 6,
    images: [{ public_id: "bag1", url: "/bags/b1.png" }],
    brand: "TechBag",
    discount: 5,
    ratings: 4.6,
    numReviews: 21,
    isFeatured: true,
    color: ["مشکی"],
    size: ["بزرگ"],
    weight: 1.3,
    dimensions: { width: 38, height: 28, depth: 10 },
    warranty: "2 سال",
  },
  {
    name: "کیف مدرسه دخترانه طرح یونیکورن",
    description: "طرح فانتزی و جادار برای کودکان.",
    sku: "SCH-006",
    price: 450000,
    category: "کیف",
    subcategories: "کیف مدرسه",
    stock: 12,
    images: [{ public_id: "bag1", url: "/bags/b7.png" }],
    brand: "Kido",
    ratings: 4.1,
    numReviews: 17,
    isFeatured: false,
    color: ["بنفش", "صورتی"],
    size: ["متوسط"],
    weight: 0.7,
    dimensions: { width: 28, height: 35, depth: 13 },
    warranty: "6 ماه",
  },
  {
    name: "کیف چرم دستی مردانه",
    description: "ساخته شده از چرم گاوی با کیفیت بالا.",
    sku: "LTH-007",
    price: 1100000,
    category: "کیف",
    subcategories: "کیف چرم",
    stock: 5,
    images: [{ public_id: "bag1", url: "/bags/b4.png" }],
    brand: "RoyalLeather",
    ratings: 4.7,
    numReviews: 11,
    isFeatured: true,
    color: ["قهوه‌ای"],
    size: ["متوسط"],
    weight: 0.6,
    dimensions: { width: 28, height: 20, depth: 7 },
    warranty: "2 سال",
  },
  {
    name: "کیف ورزشی ضدآب",
    description: "مناسب باشگاه و سفرهای کوتاه.",
    sku: "SPB-008",
    price: 670000,
    category: "کیف",
    subcategories: "کیف ورزشی",
    stock: 9,
    images: [{ public_id: "bag1", url: "/bags/b3.png" }],
    brand: "Sportify",
    ratings: 4.4,
    numReviews: 19,
    isFeatured: false,
    color: ["آبی", "طوسی"],
    size: ["بزرگ"],
    weight: 1.1,
    dimensions: { width: 45, height: 30, depth: 20 },
    warranty: "1 سال",
  },
  {
    name: "کیف زنانه طرح جدید ۲۰۲۵",
    description: "ترند جدید بازار با طراحی متفاوت و جادار.",
    sku: "WMN-009",
    price: 750000,
    category: "کیف",
    subcategories: "کیف زنانه",
    stock: 14,
    images: [{ public_id: "bag9", url: "/bags/b5.png" }],
    brand: "Trendista",
    discount: 20,
    ratings: 4.9,
    numReviews: 34,
    isFeatured: true,
    color: ["مشکی", "سبز زیتونی"],
    size: ["متوسط"],
    weight: 0.8,
    dimensions: { width: 30, height: 22, depth: 10 },
    warranty: "1 سال",
  },
  {
    name: "کیف مردانه اداری",
    description: "طراحی ساده، رسمی و مقاوم برای جلسات کاری.",
    sku: "MEN-010",
    price: 880000,
    category: "کیف",
    subcategories: "کیف مردانه",
    stock: 7,
    images: [{ public_id: "bag10", url: "/bags/b8.png" }],
    brand: "BizPro",
    ratings: 4.2,
    numReviews: 16,
    isFeatured: false,
    color: ["مشکی"],
    size: ["بزرگ"],
    weight: 1.2,
    dimensions: { width: 40, height: 28, depth: 12 },
    warranty: "1 سال",
  },
  // accessoris *************************************************************************************************
  {
    name: "دستبند استیل طرح مینیمال",
    description: "دستبندی زیبا از جنس استیل ضد زنگ با طراحی مینیمال.",
    sku: "BR-101",
    price: 180000,
    category: "اکسسوری",
    subcategories: "دستبند",
    stock: 20,
    images: [{ public_id: "acc1", url: "/accessories/a1.png" }],
    brand: "SilverArt",
    ratings: 4.4,
    numReviews: 12,
    isFeatured: true,
    color: ["نقره‌ای", "طلایی"],
    size: ["فری سایز"],
    weight: 0.1,
    dimensions: { width: 6, height: 0.5, depth: 6 },
    warranty: "6 ماه",
  },
  {
    name: "کمربند چرمی مردانه اصل",
    description: "کمربند از چرم طبیعی مناسب برای استفاده روزمره و رسمی.",
    sku: "LB-102",
    price: 320000,
    category: "اکسسوری",
    subcategories: "کمربند چرم",
    stock: 10,
    images: [{ public_id: "acc2", url: "/accessories/a5.png" }],
    brand: "LeatherZone",
    ratings: 4.7,
    numReviews: 20,
    isFeatured: false,
    color: ["قهوه‌ای", "مشکی"],
    size: ["M", "L", "XL"],
    weight: 0.3,
    dimensions: { width: 120, height: 4, depth: 0.5 },
    warranty: "1 سال",
  },
  {
    name: "کلاه بافتنی زمستانی",
    description: "کلاه گرم و راحت برای فصول سرد سال.",
    sku: "HT-103",
    price: 120000,
    category: "اکسسوری",
    subcategories: "کلاه",
    stock: 25,
    images: [{ public_id: "acc3", url: "/accessories/a6.png" }],
    brand: "Wooly",
    ratings: 4.1,
    numReviews: 8,
    isFeatured: true,
    color: ["خاکستری", "آبی نفتی"],
    size: ["فری سایز"],
    weight: 0.2,
    dimensions: { width: 22, height: 20, depth: 2 },
    warranty: "3 ماه",
  },
  {
    name: "گردنبند زنانه سنگی",
    description: "گردنبند ساخته‌شده از سنگ‌های نیمه‌قیمتی.",
    sku: "NK-104",
    price: 250000,
    category: "اکسسوری",
    subcategories: "گردنبند",
    stock: 18,
    images: [{ public_id: "acc4", url: "/accessories/a7.png" }],
    brand: "GemStyle",
    ratings: 4.5,
    numReviews: 14,
    isFeatured: false,
    color: ["سبز", "مشکی"],
    size: ["فری سایز"],
    weight: 0.15,
    dimensions: { width: 30, height: 0.5, depth: 30 },
    warranty: "1 سال",
  },
  {
    name: "عینک آفتابی کلاسیک",
    description: "عینک با فریم کلاسیک مناسب روزهای آفتابی.",
    sku: "SG-105",
    price: 450000,
    category: "اکسسوری",
    subcategories: "عینک آفتابی",
    stock: 16,
    images: [{ public_id: "acc5", url: "/accessories/a2.png" }],
    brand: "SunVision",
    ratings: 4.6,
    numReviews: 22,
    isFeatured: true,
    color: ["مشکی", "قهوه‌ای"],
    size: ["فری سایز"],
    weight: 0.3,
    dimensions: { width: 14, height: 5, depth: 3 },
    warranty: "1 سال",
  },
  {
    name: "کمربند فانتزی زنانه",
    description: "کمربند باریک مناسب لباس‌های مجلسی.",
    sku: "BT-109",
    price: 150000,
    category: "اکسسوری",
    subcategories: "کمربند",
    stock: 15,
    images: [{ public_id: "acc9", url: "/accessories/a4.png" }],
    brand: "ElegantStyle",
    ratings: 4.2,
    numReviews: 9,
    isFeatured: false,
    color: ["طلایی", "رزگلد"],
    size: ["S", "M"],
    weight: 0.1,
    dimensions: { width: 100, height: 2, depth: 0.3 },
    warranty: "3 ماه",
  },
  {
    name: "ست جواهرات طرح یاقوت",
    description: "ست شامل گردنبند، دستبند و گوشواره با سنگ مصنوعی.",
    sku: "JW-110",
    price: 850000,
    category: "اکسسوری",
    subcategories: "جواهرات",
    stock: 6,
    images: [{ public_id: "acc10", url: "/accessories/a3.png" }],
    brand: "RubyQueen",
    ratings: 4.9,
    numReviews: 26,
    isFeatured: true,
    color: ["قرمز", "نقره‌ای"],
    size: ["فری سایز"],
    weight: 0.5,
    dimensions: { width: 30, height: 5, depth: 30 },
    warranty: "1 سال",
  },
  // glasses *************************************************************************************************

  {
    name: "عینک آفتابی مدل کلاسیک",
    description: "عینک آفتابی با فریم مقاوم و شیشه UV400.",
    sku: "GL-201",
    price: 480000,
    category: "عینک",
    subcategories: "عینک آفتابی",
    stock: 25,
    images: [{ public_id: "gl1", url: "/glasses/b1.png" }],
    brand: "SunX",
    ratings: 4.5,
    numReviews: 18,
    isFeatured: true,
    color: ["مشکی", "قهوه‌ای"],
    size: ["فری سایز"],
    weight: 0.2,
    dimensions: { width: 14, height: 4.5, depth: 3 },
    warranty: "1 سال",
  },
  {
    name: "عینک طبی فریم فلزی",
    description: "عینک طبی سبک و بادوام مناسب استفاده روزانه.",
    sku: "GL-202",
    price: 620000,
    category: "عینک",
    subcategories: "عینک طبی",
    stock: 30,
    images: [{ public_id: "gl2", url: "/glasses/b5.png" }],
    brand: "OpticLine",
    ratings: 4.7,
    numReviews: 14,
    isFeatured: false,
    color: ["طلایی", "نقره‌ای"],
    size: ["فری سایز"],
    weight: 0.15,
    dimensions: { width: 13, height: 4, depth: 2.5 },
    warranty: "2 سال",
  },
  {
    name: "عینک ورزشی ضد ضربه",
    description: "عینک ایمنی با لنز ضد خش مخصوص ورزشکاران.",
    sku: "GL-203",
    price: 700000,
    category: "عینک",
    subcategories: "عینک ورزشی",
    stock: 10,
    images: [{ public_id: "gl3", url: "/glasses/b3.png" }],
    brand: "SportVision",
    ratings: 4.6,
    numReviews: 22,
    isFeatured: true,
    color: ["قرمز", "آبی"],
    size: ["فری سایز"],
    weight: 0.25,
    dimensions: { width: 15, height: 5, depth: 3.5 },
    warranty: "1 سال",
  },
  {
    name: "عینک غواصی حرفه‌ای",
    description: "مناسب غواصی با لنزهای ضد بخار و بند قابل تنظیم.",
    sku: "GL-204",
    price: 850000,
    category: "عینک",
    subcategories: "عینک غواصی",
    stock: 8,
    images: [{ public_id: "gl4", url: "/glasses/b4.png" }],
    brand: "DivePro",
    ratings: 4.8,
    numReviews: 10,
    isFeatured: true,
    color: ["مشکی", "آبی"],
    size: ["فری سایز"],
    weight: 0.35,
    dimensions: { width: 16, height: 6, depth: 4 },
    warranty: "1 سال",
  },
  {
    name: "عینک کودک رنگی",
    description: "عینک سبک با طراحی کودکانه و رنگ‌های جذاب.",
    sku: "GL-205",
    price: 380000,
    category: "عینک",
    subcategories: "عینک کودک",
    stock: 20,
    images: [{ public_id: "gl5", url: "/glasses/b6.png" }],
    brand: "KidOptics",
    ratings: 4.4,
    numReviews: 9,
    isFeatured: false,
    color: ["صورتی", "آبی"],
    size: ["فری سایز"],
    weight: 0.1,
    dimensions: { width: 12, height: 4, depth: 2 },
    warranty: "6 ماه",
  },
  {
    name: "عینک گرافیکی ویژه گیمینگ",
    description: "عینک با فیلتر نور آبی برای کاهش خستگی چشم در استفاده طولانی.",
    sku: "GL-207",
    price: 520000,
    category: "عینک",
    subcategories: "عینک گرافیکی",
    stock: 14,
    images: [{ public_id: "gl7", url: "/glasses/b2.png" }],
    brand: "BlueShield",
    ratings: 4.6,
    numReviews: 13,
    isFeatured: true,
    color: ["مشکی", "خاکستری"],
    size: ["فری سایز"],
    weight: 0.2,
    dimensions: { width: 14, height: 4.2, depth: 3 },
    warranty: "1 سال",
  },
  // shoes *************************************************************************************************

  {
    name: "کفش اسپرت راحتی مدل 2025",
    description: "کفش اسپرت مناسب استفاده روزمره با طراحی ارگونومیک.",
    sku: "SH-101",
    price: 780000,
    category: "کفش",
    subcategories: "کفش اسپرت",
    stock: 40,
    images: [{ public_id: "sh1", url: "/shoes/s5.png" }],
    brand: "FitWalk",
    ratings: 4.5,
    numReviews: 30,
    isFeatured: true,
    color: ["سفید", "مشکی"],
    size: ["40", "41", "42", "43"],
    weight: 0.8,
    dimensions: { width: 30, height: 12, depth: 10 },
    warranty: "6 ماه",
  },
  {
    name: "کفش رسمی چرم طبیعی",
    description: "کفش رسمی مردانه مناسب مراسم و محیط اداری.",
    sku: "SH-102",
    price: 1200000,
    category: "کفش",
    subcategories: "کفش رسمی",
    stock: 25,
    images: [{ public_id: "sh2", url: "/shoes/s1.png" }],
    brand: "Eleganzo",
    ratings: 4.8,
    numReviews: 21,
    isFeatured: true,
    color: ["مشکی", "قهوه‌ای"],
    size: ["40", "41", "42", "44"],
    weight: 0.9,
    dimensions: { width: 32, height: 11, depth: 10 },
    warranty: "1 سال",
  },
  {
    name: "صندل زنانه راحتی",
    description: "صندل سبک با کفی نرم برای پیاده‌روی طولانی.",
    sku: "SH-103",
    price: 450000,
    category: "کفش",
    subcategories: "صندل",
    stock: 30,
    images: [{ public_id: "sh3", url: "/shoes/s6.png" }],
    brand: "SoftStep",
    ratings: 4.2,
    numReviews: 17,
    isFeatured: false,
    color: ["بژ", "سفید"],
    size: ["37", "38", "39", "40"],
    weight: 0.4,
    dimensions: { width: 28, height: 10, depth: 8 },
    warranty: "6 ماه",
  },
  {
    name: "کفش راحتی اسفنجی",
    description: "مناسب استفاده روزمره با کفی مموری فوم.",
    sku: "SH-104",
    price: 670000,
    category: "کفش",
    subcategories: "کفش راحتی",
    stock: 50,
    images: [{ public_id: "sh4", url: "/shoes/s7.png" }],
    brand: "EveryStep",
    ratings: 4.4,
    numReviews: 19,
    isFeatured: false,
    color: ["طوسی", "آبی"],
    size: ["39", "40", "41", "42"],
    weight: 0.6,
    dimensions: { width: 30, height: 11, depth: 9 },
    warranty: "6 ماه",
  },
  {
    name: "کفش کوهنوردی ضدآب",
    description: "مناسب صعود و مسیرهای سخت با زیره مقاوم.",
    sku: "SH-105",
    price: 1450000,
    category: "کفش",
    subcategories: "کفش کوهنوردی",
    stock: 15,
    images: [{ public_id: "sh5", url: "/shoes/s3.png" }],
    brand: "MountainForce",
    ratings: 4.9,
    numReviews: 23,
    isFeatured: true,
    color: ["زیتونی", "مشکی"],
    size: ["41", "42", "43", "44"],
    weight: 1.2,
    dimensions: { width: 34, height: 14, depth: 12 },
    warranty: "1 سال",
  },
  {
    name: "کفش ورزشی زنانه سبک",
    description: "کفش نرم و سبک مناسب باشگاه و دویدن.",
    sku: "SH-106",
    price: 820000,
    category: "کفش",
    subcategories: "کفش ورزشی زنانه",
    stock: 20,
    images: [{ public_id: "sh6", url: "/shoes/s8.png" }],
    brand: "RunFit",
    ratings: 4.3,
    numReviews: 15,
    isFeatured: false,
    color: ["صورتی", "مشکی"],
    size: ["37", "38", "39", "40"],
    weight: 0.5,
    dimensions: { width: 29, height: 10, depth: 9 },
    warranty: "9 ماه",
  },
  {
    name: "کفش ورزشی مردانه حرفه‌ای",
    description: "کفش مناسب تمرینات سنگین با جذب شوک بالا.",
    sku: "SH-107",
    price: 930000,
    category: "کفش",
    subcategories: "کفش ورزشی مردانه",
    stock: 28,
    images: [{ public_id: "sh7", url: "/shoes/s4.png" }],
    brand: "ProStep",
    ratings: 4.7,
    numReviews: 26,
    isFeatured: true,
    color: ["خاکستری", "آبی"],
    size: ["41", "42", "43", "44"],
    weight: 0.85,
    dimensions: { width: 31, height: 12, depth: 10 },
    warranty: "1 سال",
  },
  {
    name: "چکمه چرمی بلند",
    description: "چکمه ضد آب با آستر گرم مناسب فصل زمستان.",
    sku: "SH-108",
    price: 1600000,
    category: "کفش",
    subcategories: "چکمه",
    stock: 12,
    images: [{ public_id: "sh8", url: "/shoes/s2.png" }],
    brand: "LeatherBoots",
    ratings: 4.6,
    numReviews: 13,
    isFeatured: true,
    color: ["قهوه‌ای", "مشکی"],
    size: ["38", "39", "40", "41"],
    weight: 1.1,
    dimensions: { width: 33, height: 18, depth: 12 },
    warranty: "1 سال",
  },
  // watches *************************************************************************************************

  {
    name: "ساعت مچی مردانه استیل کلاسیک",
    description: "ساعت مقاوم با طراحی شیک و موتور ژاپنی.",
    sku: "WA-101",
    price: 1450000,
    category: "ساعت",
    subcategories: "ساعت مچی مردانه",
    stock: 20,
    images: [{ public_id: "wa1", url: "/watch/w4.png" }],
    brand: "TimeMaster",
    ratings: 4.7,
    numReviews: 22,
    isFeatured: true,
    color: ["نقره‌ای", "مشکی"],
    size: ["فری سایز"],
    weight: 0.2,
    dimensions: { width: 4, height: 1, depth: 0.5 },
    warranty: "2 سال",
  },
  {
    name: "ساعت مچی زنانه بند چرمی",
    description: "طراحی ظریف با بند چرم اصل مناسب مجالس.",
    sku: "WA-102",
    price: 980000,
    category: "ساعت",
    subcategories: "ساعت مچی زنانه",
    stock: 18,
    images: [{ public_id: "wa2", url: "/watch/w2.png" }],
    brand: "ElegantTime",
    ratings: 4.5,
    numReviews: 17,
    isFeatured: true,
    color: ["طلایی", "قهوه‌ای"],
    size: ["فری سایز"],
    weight: 0.18,
    dimensions: { width: 3.5, height: 1, depth: 0.5 },
    warranty: "1 سال",
  },
  {
    name: "ساعت هوشمند نسل جدید",
    description: "پشتیبانی از تماس، پیامک، سنجش ضربان قلب و فعالیت‌های ورزشی.",
    sku: "WA-103",
    price: 1950000,
    category: "ساعت",
    subcategories: "ساعت هوشمند",
    stock: 35,
    images: [{ public_id: "wa3", url: "/watch/w6.png" }],
    brand: "SmartNow",
    ratings: 4.6,
    numReviews: 30,
    isFeatured: true,
    color: ["مشکی", "طوسی"],
    size: ["فری سایز"],
    weight: 0.25,
    dimensions: { width: 4.5, height: 1.2, depth: 0.6 },
    warranty: "1 سال",
  },
  {
    name: "ساعت لوکس اتوماتیک با صفحه شیشه‌ای",
    description: "ساعت لوکس مخصوص کلکسیونرها با طراحی دست‌ساز.",
    sku: "WA-104",
    price: 4800000,
    category: "ساعت",
    subcategories: "ساعت لوکس",
    stock: 6,
    images: [{ public_id: "wa4", url: "/watch/w5.png" }],
    brand: "Royale",
    ratings: 4.9,
    numReviews: 12,
    isFeatured: true,
    color: ["طلایی", "مشکی"],
    size: ["فری سایز"],
    weight: 0.3,
    dimensions: { width: 4.2, height: 1.1, depth: 0.6 },
    warranty: "5 سال",
  },
  {
    name: "ساعت کلاسیک عقربه‌ای چرمی",
    description: "سبک کلاسیک با صفحه مینیمال و بند چرم طبیعی.",
    sku: "WA-105",
    price: 1100000,
    category: "ساعت",
    subcategories: "ساعت کلاسیک",
    stock: 22,
    images: [{ public_id: "wa5", url: "/watch/w3.png" }],
    brand: "RetroWatch",
    ratings: 4.3,
    numReviews: 15,
    isFeatured: false,
    color: ["قهوه‌ای", "کرم"],
    size: ["فری سایز"],
    weight: 0.2,
    dimensions: { width: 4, height: 1, depth: 0.5 },
    warranty: "2 سال",
  },
  {
    name: "ساعت ورزشی ضدآب",
    description: "مناسب برای شنا و ورزش‌های پرتحرک با امکانات متعدد.",
    sku: "WA-106",
    price: 890000,
    category: "ساعت",
    subcategories: "ساعت ورزشی",
    stock: 28,
    images: [{ public_id: "wa6", url: "/watch/w1.png" }],
    brand: "SportiveX",
    ratings: 4.6,
    numReviews: 20,
    isFeatured: true,
    color: ["آبی", "قرمز"],
    size: ["فری سایز"],
    weight: 0.23,
    dimensions: { width: 4.3, height: 1.2, depth: 0.5 },
    warranty: "1 سال",
  },
];
